const char destinations[48][47] = {
  "EC 193 | Memmingen, München Hbf",
  "IR 35 | Zürich HB, Bern",
  "RE 54 | Versam-Safien, Ilanz",
  "IR 54 | Arosa",
  "IC 3 | Basel",
  "RJX | Wien Hbf",
  "IR 54 | Einsiedeln",
  "RE 51 | Netstal, Linthal",
  "IC 53 | Spiez, Brig",
  "NJ | Wien Hbf / Budapest / Prag",
  "RE 55 | Uznach, Nesslau",
  "IR 51 | Filisur, St. Moritz",
  "IR 53 | Romanshorn",
  "IR 52 | Rheineck",
  "IR 13 | Chur",
  "S4 | Salez-Sennwald, St. Gallen",
  "TGV 9266 | Mulhouse, Paris Gare de Lyon",
  "RE 52 | Klosters, Davos",
  "RE 53 | Chur, Thusis",
  "IC 54 | Lugano",
  "ICE | Chur",
  "IC 57 | Bern, Lausanne",
  "IC 51 | Konstanz",
  "RE | Heerbrugg, St. Gallen",
  "RE 55 | Lavin, Scuol-Tarasp",
  "RJX | Zürich HB",
  "S12 | Landquart, Chur",
  "ICE | Basel Bad Bahnhof, Hamburg-Altona",
  "S4 | Rorschach, Wattwil",
  "IR 35 | Chur",
  "RE 53 | Alstätten, Appenzell",
  "RE 51 | Klosters, Susch",
  "S4 | Walenstadt, Uznach",
  "IC 3 | Chur",
  "TGV 9580 | Belfort-Montbéliard, Lyon Part Dieu",
  "IR 51 | Wintherthur, Schaffhausen",
  "IR 53 | Andermatt",
  "IR 55 | Zernez, Tirano",
  "RE 54 | St. Margarethen",
  "IR 13 | Heerbrugg, St. Gallen",
  "IC 52 | Winterthur",
  "IR 52 | Tarasp",
  "IR 55 | Appenzell",
  "S4 | Rorschach, Herisau",
  "RE 52 | Siebnen-Wangen, Pfäffikon",
  "RJX | Salzburg Hbf",
  "IC 55 | Oerlikon, Aarau",
  "IC 56 | Koblenz, Basel"
};
